
export const ROLES = {
  ACCOUNT_MANAGER:'ACCOUNT_MANAGER',
  INVENTORY_MANAGER:'INVENTORY_MANAGER',
  DEALER_MANAGER:'DEALER_MANAGER',
  SUPER_ADMIN:'SUPER_ADMIN',
  ADMIN:'ADMIN',
  DEALER:'DEALER'
};

export const MENU_NAME = {
  ACCOUNTS:'Accounts',
  ACCOUNTS_VERIFIED_TRANSACTION:'Verified Transaction',
  ACCOUNTS_UNVERIFIED_TRANSACTION:'Unverified Transaction',
  INVENTORY:'Inventory',
  INVENTORY_VERIFIED_REQUISITION:'Verified Requisition',
  INVENTORY_UNVERIFIED_REQUISITION:'Unverified Requisition',
  INVENTORY_UNDER_PROCESSING_REQUISITION:'Under Processing Requisition',
  INVENTORY_COMPLETE_REQUISITION:'Complete Requisition',
  DEALER_MANAGER:'Dealer Manager',
  VERIFIED_DEALER:'Verified Dealer',
  UNVERIFIED_DEALER:'Unverified Dealer',
  DEALER:'Dealer',
  DEALER_SHOP:'Shop',
  DEALER_CART:'Cart',
  DEALER_PURCHASE_HISTORY:'Purchase History',
  BRAND:'Brand',
  BRAND_LIST:'Brand List',
  BRAND_ADD:'Add Brand',
  SUB_CATEGORY:'Sub Category',
  SUB_CATEGORY_LIST:'Sub Category List',
  SUB_CATEGORY_ADD:'Add Sub Category',
  CATEGORY:'Category',
  CATEGORY_LIST:' Category List',
  CATEGORY_ADD:'Add Category',
  PRODUCT: 'Product',
  EMPLOYYE:'Employee',
  DEALER_COMPLETED_REQUISITION:'Completed Requisition',
  EMPLOYYE_LIST:' Emplyee List',
  EMPLOYYE_ADD:'Add Employee',
  PRJ_DASHBOARD: 'ড্যাশবোর্ড​',
  PRJ_OVERVIEW:' প্রকল্প সার-সংক্ষেপ',
  PRJ_MEMBER:'প্রকল্পের সদস্য',
  PRJ_ADD:'নতুন প্রকল্প তৈরি',
  PRJ_LIST:'প্রকল্প তালিকা',
  EMP_LIST:'কর্মচারীর তালিকা',
  PRJ_TASK_ADD:'নতুন কার্য তৈরি',
  PRJ_TASK_LIST:'কার্য তালিকা',
  PRODUCT_ADD: 'New Product',
  PRODUCT_LIST: 'Product List',
  REPORT: 'রিপোর্ট',
  PRJ_REPORT: 'প্রকল্পের রিপোর্ট',
  PRJ_GRANTT_CHART:'গ্যান্ট চার্ট',
  MASTER_SETTING : 'মাস্টার সেটিংস',
  USER_ROLES: 'ইউজার-রোল',
  USER_PERMISSION: 'অনুমতি'
};

export const URL = {
  DEALER_COMPLETED_REQUISITION:'/dealer/completed',
  ACCOUNTS:'/accounts',
  ACCOUNTS_VERIFIED_TRANSACTION:'/accounts/verified-transaction',
  ACCOUNTS_UNVERIFIED_TRANSACTION:'/accounts/unverified-transaction',
  INVENTORY:'/inventory',
  INVENTORY_VERIFIED_REQUISITION:'/inventory/verified-requisition',
  INVENTORY_UNVERIFIED_REQUISITION:'/inventory/unverified-requisition',
  INVENTORY_UNDER_PROCESSING_REQUISITION:'/inventory/under-processing-requisition',
  INVENTORY_COMPLETE_REQUISITION:'inventory/complete-requisition',
  DEALER_MANAGER:'/dealer-manager',
  VERIFIED_DEALER:'/dealer-manager/verified-dealer',
  UNVERIFIED_DEALER:'/dealer-manager/unverified-dealer',
  DEALER:'/dealer',
  DEALER_SHOP:'/dealer/dealer-shop',
  DEALER_CART:'/dealer/dealer-cart',
  DEALER_PURCHASE_HISTORY:'/dealer/dealer-purchase-history',
  BRAND:'/brand',
  BASE_HREF:'/grp',
  PRJ_DASHBOARD: '/dashboard',
  PRODUCT: '/product',
  CATEGORY: '/category',
  CATEGORY_ADD: '/category/category-add',
  CATEGORY_LIST: '/category/category-list',
  SUB_CATEGORY: '/sub-category',
  SUB_CATEGORY_ADD: '/sub-category/sub-category-add',
  SUB_CATEGORY_LIST: '/sub-category/sub-category-list',
  EMPLOYEE: '/employee',
  EMPLOYEE_ADD: '/employee/employee-add',
  EMPLOYEE_LIST: '/employee/employee-list',
  PRJ_MEMBER:'/prj-member-list',
  PRJ_OVERVIEW:'/overview',
  PRJ_OVERVIEW_ID:'/overview/prj-overview/',
  PRJ_ADD:'/prj/prj-add',
  PRJ_LIST:'/prj/prj-list',
  PRJ_TASK_ADD:'/prj/prj-task-add',
  PRJ_TASK_LIST:'/prj/prj-task-list',
  PRODUCT_ADD: '/product/product-add',
  PRODUCT_LIST: '/product/product-list',
  BRAND_ADD: '/brand/brand-add',
  BRAND_LIST: '/brand/brand-list',
  REPORT: '/report',
  PRJ_REPORT: '/prj-report',
  PRJ_GRANTT_CHART:'/prj/prj-grant-chart',
  MASTER_SETTING: '/master-setting',
  USER_ROLES : '/master-setting/user-roles',
  USER_PERMISSION: '/master-setting/permission'
};
export const URL_NAME = {
  ACCOUNTS:'accounts',
  ACCOUNTS_VERIFIED_TRANSACTION:'verified-transaction',
  ACCOUNTS_UNVERIFIED_TRANSACTION:'unverified-transaction',
  INVENTORY:'inventory',
  INVENTORY_VERIFIED_REQUISITION:'verified-requisition',
  INVENTORY_UNVERIFIED_REQUISITION:'unverified-requisition',
  INVENTORY_UNDER_PROCESSING_REQUISITION:'under-processing-requisition',
  INVENTORY_COMPLETE_REQUISITION:'complete-requisition',
  DEALER_MANAGER:'dealer-manager',
  VERIFIED_DEALER:'verified-dealer',
  UNVERIFIED_DEALER:'unverified-dealer',
  DEALER:'dealer',
  DEALER_SHOP:'dealer-shop',
  DEALER_CART:'dealer-cart',
  DEALER_COMPLETED_REQUISITION:'completed',
  DEALER_PURCHASE_HISTORY:'dealer-purchase-history',
  WELCOME:'welcome',
  BRAND:'brand',
  BRAND_ADD:'brand-add',
  BRAND_LIST:'brand-list',
  SUB_CATEGORY:'sub-category',
  SUB_CATEGORY_ADD:'sub-category-add',
  SUB_CATEGORY_LIST:'sub-category-list',
  CATEGORY:'category',
  CATEGORY_LIST:'category-list',
  CATEGORY_ADD:'category-add',
  PRJ_DASHBOARD: 'dashboard',
  OVERVIEW:'overview',
  PRJ_OVERVIEW:'prj-overview',
  PRJ_OVERVIEW_ID:'prj-overview/:id',
  EMPLOYEE:'employee',
  EMPLOYEE_ADD:'employee-add',
  EMPLOYEE_LIST:'employee-list',
  PRJ:'prj',
  PRJ_MEMBER:'prj-member-list',
  PRJ_ADD:'prj-add',
  PRJ_LIST:'prj-list',
  PRJ_TASK_ADD:'prj-task-add',
  PRJ_TASK_LIST:'prj-task-list',
  PRODUCT:'product',
  PRODUCT_ADD: 'product-add',
  PRODUCT_LIST: 'product-list',
  REPORT: 'report',
  EMP_LIST:'employee-list',
  PRJ_REPORT: 'prj-report',
  PRJ_GRANTT_CHART:'prj-grantt-chart',
  MASTER_SETTING: 'master-setting',
  USER_ROLES : 'user-roles',
  USER_PERMISSION : 'permission'
};
export const ICON = {
  ACCOUNTS:'fa fa-credit-card',
  ACCOUNTS_VERIFIED_TRANSACTION:'fa fa-credit-card-alt',
  ACCOUNTS_UNVERIFIED_TRANSACTION:'fa fa-cc-amex',
  INVENTORY:'fa fa-spinner',
  INVENTORY_VERIFIED_REQUISITION:'fa fa-check',
  INVENTORY_UNVERIFIED_REQUISITION:'fa fa-window-close',
  INVENTORY_UNDER_PROCESSING_REQUISITION:'fa fa-spinner',
  INVENTORY_COMPLETE_REQUISITION:'fa fa-check-square-o',
  DEALER_MANAGER:'icon-globe',
  VERIFIED_DEALER:'icon-user-following',
  UNVERIFIED_DEALER:'icon-user-unfollow',
  DEALER:'icon-people',
  DEALER_SHOP:'icon-basket-loaded',
  DEALER_CART:'icon-paper-clip',
  DEALER_PURCHASE_HISTORY:'icon-briefcase',
  DEALER_COMPLETED_REQUISITION:'fa fa-check-square-o',
  BRAND:'icon-tag',
  BRAND_ADD:'icon-puzzle',
  BRAND_LIST: 'icon-list',
  CATEGORY:'icon-menu',
  CATEGORY_ADD: 'icon-plus',
  CATEGORY_LIST: 'icon-eyeglass',
  PRODUCT:'icon-basket-loaded',
  PRODUCT_ADD: 'icon-plus',
  PRODUCT_LIST: 'icon-basket',
  SUB_CATEGORY:'icon-book-open',
  SUB_CATEGORY_ADD:'icon-wrench',
  SUB_CATEGORY_LIST:'icon-directions',
  EMPLOYEE:'icon-user',
  EMPLOYEE_ADD:'icon-user-following',
  EMPLOYEE_LIST:'icon-people',
  // PRJ_DASHBOARD: 'icon-speedometer',
  // PRJ_OVERVIEW:'icon-speedometer',
  // PRJ_ADD:'icon-plus',
  // PRJ_LIST:'icon-list',
  // PRJ_TASK_ADD:'icon-plus',
  // PRJ_TASK_LIST:'icon-list',
  
  // REPORT: 'icon-drop',
  // PRJ_REPORT: 'icon-list',
  // PRJ_GRANTT_CHART:'icon-list',
  // MASTER_SETTING: 'icon-settings',
  // USER_ROLES : 'icon-location-pin',
  // USER_PERMISSION : 'icon-location-pin'
};

